from car_park_puzzle.game_board import Board,Car

def map1():
    tablero = Board(9, 9)
    tablero.add_car(Car('A', 2, 'H', 5, 0))
    tablero.add_car(Car('C', 3, 'V', 3, 2))
    tablero.add_car(Car('D', 4, 'H', 6, 2))
    tablero.add_car(Car('E', 2, 'V', 6, 1))
    tablero.add_car(Car('F', 2, 'V', 6, 6))
    tablero.add_car(Car('B', 1, "H", 0, 0, movable=False))
    tablero.add_car(Car('B', 1, "H", 3, 1, movable=False))
    tablero.add_car(Car('B', 1, "H", 1, 2, movable=False))
    tablero.add_car(Car('B', 1, "H", 3, 7, movable=False))
    tablero.add_car(Car('B', 1, "H", 8, 7, movable=False))

    
    
    return tablero


def map2():
    tablero = Board(5, 7)
    tablero.add_car(Car('A', 3, 'H', 2, 0))
    tablero.add_car(Car('C', 2, 'H', 0, 0))
    tablero.add_car(Car('E', 2, 'H', 1, 0))
    tablero.add_car(Car('K', 2, 'H', 3, 0))
    tablero.add_car(Car('H', 2, 'H', 4, 1))
    tablero.add_car(Car('J', 2, 'H', 0, 2))
    tablero.add_car(Car('F', 2, 'V', 1, 3))
    tablero.add_car(Car('L', 2, 'H', 3, 2))
    tablero.add_car(Car('M', 2, 'V', 2, 4))
    tablero.add_car(Car('Y', 2, 'H', 4, 4))
    tablero.add_car(Car('N', 2, 'V', 1, 5))
    tablero.add_car(Car('P', 2, 'V', 0, 6))

    return tablero

def map3():
    tablero = Board(5, 7)
    tablero.add_car(Car('A', 3, 'H', 3, 0))
    tablero.add_car(Car('I', 2, 'V', 0, 0))
    tablero.add_car(Car('H', 2, 'V', 3, 3))
    tablero.add_car(Car('C', 2, 'H', 4, 1))
    tablero.add_car(Car('E', 2, 'H', 0, 1))
    tablero.add_car(Car('J', 2, 'H', 1, 5))
    tablero.add_car(Car('D', 2, 'V', 3, 6))
    tablero.add_car(Car('G', 2, 'H', 0, 4))
    tablero.add_car(Car('F', 2, 'V', 2, 4))
    tablero.add_car(Car('M', 2, 'V', 2, 5))
    tablero.add_car(Car('K', 2, 'H', 4, 4))
    return tablero

def map4():
    tablero = Board(5, 7)
    tablero.add_car(Car('A', 3, 'H', 2, 0))
    tablero.add_car(Car('C', 2, 'V', 1, 3))
    tablero.add_car(Car('D', 2, 'H', 3, 2))
    tablero.add_car(Car('E', 2, 'V', 1, 4))
    tablero.add_car(Car('F', 2, 'H', 0, 4))
    tablero.add_car(Car('I', 2, 'H', 0, 2))
    tablero.add_car(Car('J', 2, 'V', 0, 1))
    tablero.add_car(Car('K', 2, 'V', 3, 0))
    tablero.add_car(Car('L', 2, 'H', 4, 1))
    tablero.add_car(Car('M', 2, 'H', 1, 5))
    tablero.add_car(Car('G', 2, 'V', 2, 5))
    #tablero.add_car(Car('H', 2, 'H', 4, 5))
    return tablero

def map5():
    tablero = Board(5, 7)
    tablero.add_car(Car('A', 3, 'H', 2, 0))
    tablero.add_car(Car('L', 2, 'V', 0, 0))
    tablero.add_car(Car('K', 2, 'V', 0, 1))
    tablero.add_car(Car('J', 2, 'V', 3, 0))
    tablero.add_car(Car('H', 2, 'H', 1, 2))
    tablero.add_car(Car('E', 2, 'V', 2, 3))
    tablero.add_car(Car('D', 2, 'H', 4, 2))
    tablero.add_car(Car('C', 2, 'V', 1, 4))
    tablero.add_car(Car('M', 2, 'H', 0, 5))
    tablero.add_car(Car('G', 2, 'V', 2, 5))
    tablero.add_car(Car('I', 2, 'H', 4, 5))
    return tablero

def map6():
    tablero = Board(9, 9)
    tablero.add_car(Car('A', 3, 'H', 4, 0))
    tablero.add_car(Car('K', 2, 'H', 7, 0))
    tablero.add_car(Car('I', 2, 'H', 1, 1))
    tablero.add_car(Car('H', 2, 'V', 2, 1))
    tablero.add_car(Car('G', 2, 'V', 5, 1))
    tablero.add_car(Car('D', 2, 'H', 6, 2))
    tablero.add_car(Car('E', 2, 'H', 2, 2))
    tablero.add_car(Car('C', 3, 'V', 3, 3))
    tablero.add_car(Car('P', 2, 'H', 8, 2))
    tablero.add_car(Car('Y', 2, 'H', 0, 4))
    tablero.add_car(Car('L', 2, 'H', 3, 4))
    tablero.add_car(Car('F', 2, 'V', 6, 4))
    tablero.add_car(Car('Q', 2, 'H', 8, 5))
    tablero.add_car(Car('N', 2, 'V', 5, 5))
    tablero.add_car(Car('O', 2, 'H', 2, 6))
    tablero.add_car(Car('M', 2, 'V', 3, 6))
    tablero.add_car(Car('J', 2, 'H', 5, 6))

    tablero.add_car(Car('B', 1, 'H', 0, 0, movable=False))
    tablero.add_car(Car('B', 1, 'H', 8, 0, movable=False))
    tablero.add_car(Car('B', 1, 'H', 3, 2, movable=False))
    #tablero.add_car(Car('B', 1, 'H', 7, 3, movable=False))
    tablero.add_car(Car('B', 1, 'H', 7, 5, movable=False))
    tablero.add_car(Car('B', 1, 'H', 2, 4, movable=False))
    tablero.add_car(Car('B', 1, 'H', 1, 6, movable=False))
    tablero.add_car(Car('B', 1, 'H', 8, 7, movable=False))

    
    return tablero

def map7():
    tablero=Board(9,9)
    tablero.add_car(Car('A', 3, 'H', 3, 0)) 
    tablero.add_car(Car('K', 2, 'H', 1, 3)) 
    tablero.add_car(Car('L', 2, 'H', 2, 0)) 
    tablero.add_car(Car('M', 3, 'H', 4, 0)) 
    tablero.add_car(Car('H', 2, 'V', 2, 3)) 
    tablero.add_car(Car('N', 2, 'V', 3, 5)) 
    tablero.add_car(Car('J', 2, 'H', 4, 3)) 
    tablero.add_car(Car('W', 3, 'V', 3, 7)) 
    tablero.add_car(Car('O', 2, 'H', 5, 2)) 
    tablero.add_car(Car('Y', 2, 'H', 5, 5)) 
    tablero.add_car(Car('U', 2, 'H', 6, 0)) 
    tablero.add_car(Car('T', 2, 'H', 6, 6)) 
    tablero.add_car(Car('Q', 2, 'V', 7, 2)) 
    tablero.add_car(Car('R', 2, 'H', 8, 3)) 
    tablero.add_car(Car('B', 1, 'H', 1, 2, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 1, 7, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 2, 5, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 7, 1, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 6, 3, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 7, 5, movable=False)) 
    
    return tablero 

def map8():
    tablero = Board(9, 9)
    tablero.add_car(Car('A', 3, 'H', 5, 0)) 
    tablero.add_car(Car('I', 2, 'V', 6, 1)) 
    tablero.add_car(Car('O', 2, 'V', 0, 2)) 
    tablero.add_car(Car('P', 2, 'H', 2, 2)) 
    tablero.add_car(Car('Q', 2, 'H', 3, 1)) 
    tablero.add_car(Car('K', 3, 'V', 3, 3)) 
    tablero.add_car(Car('U', 2, 'V', 2, 4)) 
    tablero.add_car(Car('V', 2, 'H', 1, 4)) 
    tablero.add_car(Car('Y', 2, 'V', 4, 4)) 
    tablero.add_car(Car('L', 2, 'H', 6, 3)) 
    tablero.add_car(Car('M', 2, 'V', 5, 5)) 
    tablero.add_car(Car('X', 2, 'V', 5, 6)) 
    tablero.add_car(Car('R', 2, 'H', 4, 6)) 
    tablero.add_car(Car('F', 2, 'V', 7, 4)) 
    tablero.add_car(Car('G', 2, 'H', 7, 5)) 
    tablero.add_car(Car('E', 2, 'V', 6, 7)) 
    tablero.add_car(Car('B', 1, 'H', 0, 3, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 1, 7, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 2, 1, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 3, 5, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 6, 2, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 8, 0, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 8, 6, movable=False)) 

    return tablero

def map9():
    tablero = Board(9, 9)
    tablero.add_car(Car('A', 3, 'H', 5, 0)) 
    tablero.add_car(Car('I', 2, 'H', 1, 0)) 
    tablero.add_car(Car('F', 2, 'V', 3, 0))
    tablero.add_car(Car('f', 3, 'V', 4, 5))  
    tablero.add_car(Car('H', 2, 'V', 1, 3)) 
    tablero.add_car(Car('G', 2, 'H', 0, 5)) 
    tablero.add_car(Car('X', 2, 'H', 2, 7)) 
    tablero.add_car(Car('V', 3, 'H', 3, 1)) 
    tablero.add_car(Car('C', 2, 'V', 4, 3)) 
    tablero.add_car(Car('L', 2, 'H', 3, 5)) 
    tablero.add_car(Car('T', 2, 'H', 8, 3)) 
    tablero.add_car(Car('M', 2, 'V', 4, 7)) 
    tablero.add_car(Car('J', 2, 'V', 6, 1)) 
    tablero.add_car(Car('Y', 2, 'H', 6, 2)) 
    tablero.add_car(Car('U', 2, 'H', 7, 5)) 
    tablero.add_car(Car('S', 2, 'V', 7, 8)) 
    tablero.add_car(Car('P', 2, 'H', 8, 0)) 
    tablero.add_car(Car('B', 1, 'H', 0, 3, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 1, 7, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 2, 1, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 3, 4, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 3, 8, movable=False)) 
    #tablero.add_car(Car('B', 1, 'H', 5, 5, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 7, 3, movable=False)) 
    tablero.add_car(Car('B', 1, 'H', 8, 6, movable=False)) 

    return tablero

def map10():
    tablero = Board(15,15)
    tablero.add_car(Car('A', 3, 'H', 6, 0))
    tablero.add_car(Car('R', 2, 'H', 3, 0))
    tablero.add_car(Car('O', 2, 'H', 10, 0))
    tablero.add_car(Car('S', 3, 'V', 7, 1))
    tablero.add_car(Car('H', 3, 'H', 1, 2))
    tablero.add_car(Car('G', 2, 'V', 4, 2))
    tablero.add_car(Car('T', 3, 'H', 7, 2))
    tablero.add_car(Car('P', 3, 'V', 10, 2))
    tablero.add_car(Car('L', 3, 'H', 13, 1))
    tablero.add_car(Car('C', 4, 'V', 3, 3))
    tablero.add_car(Car('Y', 4, 'H', 4, 4))
    tablero.add_car(Car('J', 3, 'H', 10, 4))
    tablero.add_car(Car('U', 3, 'V', 6, 5))
    tablero.add_car(Car('K', 2, 'V', 13, 5))
    tablero.add_car(Car('X', 4, 'H', 7, 7))
    tablero.add_car(Car('W', 3, 'V', 8, 7))
    tablero.add_car(Car('V', 3, 'V', 3, 8))
    tablero.add_car(Car('D', 3, 'H', 13, 8))
    tablero.add_car(Car('Z', 3, 'V', 10, 9))
    tablero.add_car(Car('M', 2, 'H', 3, 10))
    tablero.add_car(Car('Q', 3, 'H', 10, 10))
    tablero.add_car(Car('Y', 2, 'H', 1, 11))
    tablero.add_car(Car('F', 5, 'V', 4, 11))
    tablero.add_car(Car('j', 2, 'H', 2, 12))
    tablero.add_car(Car('k', 3, 'V', 5, 12))
    tablero.add_car(Car('u', 3, 'V', 5, 13))
    tablero.add_car(Car('s', 3, 'V', 9, 13))

    tablero.add_car(Car('B', 1, 'V' , 0, 0, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 0, 14, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 9, 3, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 2, 6, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 13, 6, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 0, 9, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 13, 14, movable=False))
    return tablero
    #META(6,14)



def map11():
    tablero = Board(15,15)
    tablero.add_car(Car('A', 3, 'H', 6, 0))
    tablero.add_car(Car('K', 2, 'V', 2, 0))
    tablero.add_car(Car('S', 2, 'H', 12, 0))
    tablero.add_car(Car('P', 4, 'H', 3, 1))
    tablero.add_car(Car('I', 3, 'H', 9, 1))
    tablero.add_car(Car('C', 3, 'V', 6, 3))
    tablero.add_car(Car('D', 2, 'H', 10, 3))
    tablero.add_car(Car('W', 3, 'V', 11, 4))
    tablero.add_car(Car('G', 3, 'V', 4, 4))
    tablero.add_car(Car('H', 3, 'H', 8, 4))
    tablero.add_car(Car('Q', 3, 'H', 12, 5))
    #tablero.add_car(Car('D', 3, 'H', 13, 8))
    tablero.add_car(Car('Z', 3, 'V', 4, 6))
    tablero.add_car(Car('O', 3, 'H', 4, 7))
    tablero.add_car(Car('J', 5, 'V', 5, 7))
    tablero.add_car(Car('M', 3, 'H', 7, 8))
    tablero.add_car(Car('V', 2, 'V', 9, 8))
    tablero.add_car(Car('R', 3, 'H', 10, 9))
    tablero.add_car(Car('L', 2, 'V', 2, 10))
    tablero.add_car(Car('F', 3, 'H', 5, 10))
    tablero.add_car(Car('N', 3, 'V', 6, 11))
    tablero.add_car(Car('T', 2, 'H', 2, 12))
    tablero.add_car(Car('X', 5, 'V', 3, 13))
    tablero.add_car(Car('Y', 2, 'H', 8, 13))

    tablero.add_car(Car('B', 1, 'V' , 1, 1, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 13, 0, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 2, 3, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 10, 1, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 11, 3, movable=False))
    #tablero.add_car(Car('B', 1, 'V' , 0, 0, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 2, 5, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 7, 5, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 11, 3, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 5, 8, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 2, 9, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 13, 9, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 9, 10, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 9, 12, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 3, 12, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 14, 14, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 0, 14,movable=False))
    return tablero
    

def map12():
    tablero = Board(15,15)
    tablero.add_car(Car('A', 3, 'H', 9, 0))
    tablero.add_car(Car('Q', 2, 'H', 1, 0))
    tablero.add_car(Car('E', 2, 'H', 4, 0))
    tablero.add_car(Car('T', 2, 'H', 7, 0))
    tablero.add_car(Car('N', 3, 'H', 11, 0))
    tablero.add_car(Car('R', 2, 'H', 5, 1))
    tablero.add_car(Car('C', 3, 'V', 7, 3))
    tablero.add_car(Car('W', 3, 'V', 0, 2))
    tablero.add_car(Car('H', 3, 'H', 6, 3))
    tablero.add_car(Car('V', 2, 'V', 12, 3))
    tablero.add_car(Car('I', 2, 'H', 0, 4))
    tablero.add_car(Car('U', 2, 'V', 1, 5))
    tablero.add_car(Car('Y', 2, 'V', 3, 4))
    tablero.add_car(Car('K', 2, 'V', 4, 5))
    tablero.add_car(Car('M', 2, 'V', 8, 5))
    tablero.add_car(Car('X', 3, 'H', 12, 4))
    tablero.add_car(Car('O', 3, 'H', 2, 6))
    tablero.add_car(Car('L', 3, 'V', 8, 6))
    tablero.add_car(Car('P', 3, 'V', 3, 7))
    tablero.add_car(Car('L', 3, 'V', 8, 6))
    tablero.add_car(Car('t', 3, 'V', 4, 8))
    tablero.add_car(Car('J', 3, 'V', 9, 8))
    tablero.add_car(Car('y', 2, 'H', 3, 8))
    tablero.add_car(Car('Z', 2, 'H', 12, 8))
    tablero.add_car(Car('G', 3, 'V', 7, 9))
    tablero.add_car(Car('S', 3, 'H', 11, 9))
    tablero.add_car(Car('j', 2, 'V', 2, 10))
    tablero.add_car(Car('c', 2, 'H', 5, 10))
    tablero.add_car(Car('F', 3, 'V', 7, 11))
    tablero.add_car(Car('x', 3, 'V', 3, 12))
    tablero.add_car(Car('k', 2, 'H', 6, 13))
    tablero.add_car(Car('D', 4, 'V', 8, 13))

    tablero.add_car(Car('B', 1, 'V' , 0, 0, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 3, 1, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 0, 14, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 12, 2, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 6, 2, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 2, 4, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 5, 6, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 0, 7, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 12, 7, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 4, 10, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 14, 10, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 2, 11, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 0, 14, movable=False))
    tablero.add_car(Car('B', 1, 'V' , 14, 14,movable=False))
    tablero.add_car(Car('B', 1, 'V' , 14, 0,movable=False))
    tablero.add_car(Car('B', 1, 'V' , 12, 13,movable=False))
    return tablero      

def map13():
    pass

     